### ISSUE TITLE
The object (Sequence) is being referenced before its creation.

### ISSUE THREAD

**Issue by vladsol** [pgmodeler/pgmodeler#1462] opened 2020-07-30 08:12 UTC
pgModeler 0.9.3-beta
PostgreSQL 12.0

Trying to validate the model:
_The object datadb.client_id_seq (Sequence) [id: 4321] is being referenced by 1 object(s) before its creation._

The "datadb.client_id_seq" is present in model (in Objects list) and in DB schema too.

Steps to reproduce:
- Created table new_table
CREATE TABLE datadb.new_table (
	id integer
);
- Validation - OK
- Export - OK
- Create Sequence client_id_seq
- Validation - OK
- Export - OK
- Changed default value for datadb.new_table.id from Expression "" to Sequence (client_id_seq)
- Validation - **Error:** 
_The object datadb.client_id_seq (Sequence) [id: 4321] is being referenced by 1 object(s) before its creation._

**Comment by FireEmerald** [comment] 2020-10-07 06:48
This issue is indeed still present. It was already reported since years ago in #837.
The "Apply fixes" button does not resolve the error. Instead it leads to a infinite processing:
![sample](https://user-images.githubusercontent.com/1107939/95296917-e28eb380-0879-11eb-8b41-b40f24946717.gif)

**Comment by rkhaotix** [comment] 2020-10-07 10:30
@FireEmerald strangely I can't reproduce this bug. Do you have a sample model or the steps to reproduce this infinite validation? The steps provided by @vladsol don't seem to trigger the problem. 🤔

**Comment by FireEmerald** [comment] 2020-10-07 11:23
The error happend after the following:

1. Imported postgres database via "Import"
2. Validation fails as shown
3. Save the database as file
4. Validation fails as shown
5. Restart pgmodeler and open the saved database file
6. Validation passes

Seems like a imported database must be saved and re-opened to work properly.

**Comment by rkhaotix** [comment] 2020-10-07 11:31
Thanks @FireEmerald that seems to be a clue! I'll investigate.

**Comment by FireEmerald** [comment] 2020-10-07 11:50
@rkhaotix  I invested a little bit and hopefully you can reproduce the issue as written below:

- docker image `postgres:12.4-alpine`
- pgmodeler v0.9.2

1. Create empty database
2. Execute following sql script in `public`
<details>

```
create table table1
(
	id varchar(40) not null
		constraint PK_table1
			primary key,
	c1 varchar(255) not null,
	c2 varchar(25) not null,
	c3 varchar(25) not null
);

create table table2
(
	id serial not null
		constraint PK_table2
			primary key,
	c1 varchar(50) not null,
	c2 varchar(50) not null,
	c3 varchar(50) not null
);

create table table3
(
	id serial not null
		constraint PK_table3
			primary key,
	c1 varchar(50) not null,
	c2 varchar(50) not null,
	c3 varchar(50) not null
);

create table table4
(
	id integer not null
		constraint PK_table4
			primary key,
	c1 int not null,
	c2 int not null,
	c3 int not null,
	c4 int not null
);

create table table5
(
	id serial not null
		constraint PK_table5
			primary key,
	c1 varchar(50) not null,
	c2 varchar(50) not null,
	c3 varchar(50) not null,
	c4 int not null
);

create table table6
(
	id serial not null
		constraint PK_table6
			primary key,
	c1 varchar(50) not null,
	c2 varchar(50) not null,
	c3 int not null,
	c4 varchar(100) not null,
	c5 varchar(50) not null,
	c6 date not null,
	c7 date not null,
	c8 int not null
);

create table table7
(
	id serial not null
		constraint PK_table7
			primary key,
	c1 varchar(25) not null,
	c2 int not null,
	c3 varchar(25) not null
);

create table table8
(
	id serial not null
		constraint PK_table8
			primary key,
	c1 varchar(25) not null,
	c2 varchar(25) not null
);

create table table9
(
	id integer not null
		constraint PK_table9
			primary key,
	c1 int not null,
	c2 int not null,
	c3 int not null
);

create table table10
(
	id serial not null
		constraint PK_dummy3
			primary key,
	c1 varchar(25) not null,
	c2 varchar(25) not null,
	c3 int not null,
	c4 bigint not null,
	c5 varchar(25) not null,
	c6 varchar(50) not null,
	c7 varchar(50) not null,
	c8 varchar(25) not null,
	c9 int not null,
	c10 varchar(25) not null
);

create table table11
(
	col1 integer not null
		constraint FK_table11_table4
			references table4,
	col2 integer not null
		constraint FK_table11_table9
			references table9,
	col3 serial not null
		constraint FK_table11_table2
			references table2,
	col4 serial not null
		constraint FK_table11_table5
			references table5,
	col5 serial not null
		constraint FK_table11_table7
			references table7,
	col6 serial not null
		constraint FK_table11_table10
			references table10,
	col10 serial not null
		constraint FK_table11_table6
			references table6,
	col16 timestamp not null,
	c1 varchar(12) not null,
	c2 varchar(50) not null,
	c3 timestamp not null,
	c4 int not null,
	c5 timestamp not null,
	c6 float not null,
	c7 bigint not null,
	c8 bigint not null,
	c9 bigint not null,
	c10 bigint not null,
	c11 bigint not null
);

create table table12
(
	col1 integer not null
		constraint FK_table12_table4
			references table4,
	col2 integer not null
		constraint FK_table12_table9
			references table9,
	col9 varchar(40) not null
		constraint FK_table12_table1
			references table1,
	col3 serial not null
		constraint FK_table12_table2
			references table2,
	col7 serial not null
		constraint FK_table12_table3
			references table3,
	col8 serial not null
		constraint FK_table12_table8
			references table8,
	col4 serial not null
		constraint FK_table12_table5
			references table5,
	c1 varchar(25) not null,
	c2 bit not null,
	c3 int not null,
	c4 int not null,
	c5 int not null,
	c6 int not null,
	c7 timestamp not null,
	c8 timestamp not null,
	c9 timestamp not null,
	c10 varchar(50) not null,
	c11 int not null,
	c12 int not null,
	c13 int not null,
	c14 int not null,
	c15 int not null,
	c16 int not null,
	c17 int not null
);

create table table13
(
	col1 integer not null
		constraint FK_table13_table4
			references table4,
	col2 integer not null
		constraint FK_table13_table9
			references table9,
	col3 serial not null
		constraint FK_table13_table2
			references table2,
	col7 serial not null
		constraint FK_table13_table3
			references table3,
	col8 serial not null
		constraint FK_table13_table8
			references table8,
	col4 serial not null
		constraint FK_table13_table5
			references table5,
	c1 timestamp not null,
	c2 int not null,
	c3 varchar(50) not null,
	c4 text not null
);

create table table14
(
	col1 integer not null
		constraint FK_table14_table4
			references table4,
	col2 integer not null
		constraint FK_table14_table9
			references table9,
	col3 serial not null
		constraint FK_table14_table2
			references table2,
	col7 serial not null
		constraint FK_table14_table3
			references table3,
	col11 timestamp not null
);

create table table15
(
	col1 integer not null
		constraint FK_table15_table4
			references table4,
	col2 integer not null
		constraint FK_table15_table9
			references table9,
	col3 serial not null
		constraint FK_table15_table2
			references table2,
	col7 serial not null
		constraint FK_table15_table3
			references table3,
	c1 timestamp not null,
	c2 varchar(40) not null,
	c3 float not null,
	c4 float not null,
	c5 float not null
);

create table table16
(
	col1 integer not null
		constraint FK_dummy_table9
			references table9,
	col2 integer not null
		constraint FK_dummy_table4
			references table4,
	col3 serial not null
		constraint FK_dummy2_table2
			references table2,
	col4 serial not null
		constraint FK_dummy2_table5
			references table5,
	col5 serial not null
		constraint FK_dummy2_table7
			references table7,
	col6 serial not null
		constraint FK_dummy2_dummy3
			references table10,
	c1 timestamp not null,
	c2 int not null,
	c3 timestamp not null,
	c4 float not null,
	c5 bigint not null,
	c6 bigint not null,
	c7 bigint not null,
	c8 bigint not null,
	c9 bigint not null,
	c10 bigint not null,
	c11 bigint not null,
	c12 bigint not null,
	c13 int not null,
	c14 int not null
);
```

</details>

3. Import the database in pgmodeler
4. Try to validate it

Reproduced?

**Comment by rkhaotix** [comment] 2020-10-07 15:03
@FireEmerald Thank you so much. You nailed it! 
I've already pushed the fix! ;)

**Closed** 2020-11-09 18:01 UTC
Labels: bug, fixed
