### ISSUE TITLE
PgModeler hangs up on import DB

### ISSUE THREAD

**Issue by ilyale** [pgmodeler/pgmodeler#993] opened 2017-09-05 14:40 UTC
Trying to import from postgreSQL db v9.5 on ms virtual-pc (ms win 7 32-bit, 2Gb RAM) on host machine win 7 64, 8Gb RAM core i5
PgModeler begins import and randomly hangs up on one of tables (from 4 to 10% on progress bar).
No errors displayed. But entire process seems to be very slow (before i worked with remote serve with demo-version and all was OK). On a progress bar tables changing one per 2-3 sec intead of when working with remote server tables changing very fast (2-3 per second).
Windows task manager showing enought free resources on a host machine and on a virtual-pc too.
pgAdmin working pretty fast with this DB on virtual-pc. For example demo version of DeZign for Databases working good when importing this DB. But I already bought pgModeler and want to use it.

**Comment by ilyale** [comment] 2017-09-05 14:45
[sw-dump.txt](https://github.com/pgmodeler/pgmodeler/files/1277775/sw-dump.txt)
this is dump with my schema

**Comment by rkhaotix** [comment] 2017-09-05 16:56
Hi @ilyale 

Thanks for reporting. 
Well, I really sorry if pgModeler did not work as you've expected. The reverse engineering is a feature relatively new and many work still must be done to make it as free as possible from bugs. What I can guarantee you is that in every release the process is a bit more improved and accurate.

I'll try to debug the import process using the dump you've provided. Soon I'll report you back.

**Comment by rkhaotix** [comment] 2017-09-05 19:33
@ilyale After testing several times the import of your database what I can confirm to you is no hang-ups was detected. I'm working on 0.9.1-alpha (pratically the same codebase of 0.9.0 stable).

What I could detect is that there was a bug when importing operators and operator classes. After fixing this problem I was able to import your model without major problem. Again, the application did not  crash. The file in the attachments is the model generated by pgmodeler after the import. Please, don't forget to change its extension from txt to dbm so the application can open it properly.

I don't know what release you're using but if it was 0.9.0 it should open without issues if not... I'll provide you an snapshot of the one I'm using to test the fixes.

[sw_test.txt](https://github.com/pgmodeler/pgmodeler/files/1278639/sw_test.txt)

**Comment by j0hannes** [comment] 2017-10-17 15:33
On OSX, I see the import hanging at 90% on `Creating table inheritances...`.

Cancelling the process or closing the dialog does not work, the only way out is to force kill the application.

This is reproducible with any schema that has inherited tables or inherits tables.

**Comment by cravatebleue** [comment] 2017-12-04 03:33
I have same problem as j0hannes.

**Comment by murraypetera** [comment] 2018-03-22 15:55
+1 stuck at 90% 
0.9.1-beta demo

**Comment by raframil** [comment] 2019-10-18 00:48
+1 stuck at 90% using 0.9.1

Tried it now at 0.9.2-beta1 and looks like it worked

**Closed** 2024-01-03 16:02 UTC
Labels: oldissue
