### ISSUE TITLE
keeps crashing randomly when applying new table or relationship

### ISSUE THREAD

**Issue by Soraphiroth** [pgmodeler/pgmodeler#1428] opened 2020-05-05 20:50 UTC
**Bug description**
When I create a new table or relationship it can crash sometimes. It seems random, sometimes I can reproduce it, sometimes not.

**How to reproduce**
can't

**Expected behavior**
should not crash.

**Info about your desktop**
 - OS: Windows 10 64bit 
 - Version: 1909
 - Window manager: explorer
 - pgModeler version: 0.92 20200329
 - Qt version: 5.14.1

**Stacktrace / Debug info**
```
** pgModeler crashed after receive signal: 11 **

Date/Time: 2020-05-05 19:42:43 
Version: 0.9.2 
Build: 20200329
Compilation Qt version: 5.14.1
Running Qt version: 5.14.1
```

**Comment by rkhaotix** [comment] 2020-05-05 22:39
Did you compile it yourself? Did you try a newer version?

I've tested a lot with 0.9.3-alpha and it works fine. If possible provide more details like the steps you taken until it crashes, etc.

**Comment by Soraphiroth** [comment] 2020-05-07 09:45
I didn't try the alpha yet and I compiled it myself yes. I would like to provide more details but as I say it's random. I tried to reproduce it more than 30 minutes without success. The only thing I can say is it happens when I apply a new table/relationship or apply an edit to it.

**Comment by rkhaotix** [comment] 2021-07-29 00:44
I can't reproduce it either. I'll close this for now. Feel free to reopen it when you discover how to reproduce the bug.

**Closed by rkhaotix** 2021-07-29 00:44 UTC
