### ISSUE TITLE
Data Corrupted after upgrading to 1.0.0

### ISSUE THREAD

**Issue by nissane** [pgmodeler/pgmodeler#1757] opened 2023-03-06 20:33 UTC
**Bug description**
I store data in some of the tables, by hitting <edit data>.  After I upgraded to 1.0.0, the data is no longer stored in columns, but is stored in one large column, and it does not generate anymore. (see screenshot.)

pgmodeler does have the message "some invalid or duplicated columns were detected. In order to solve this issue double-click the header..."

Yet when I do that it just puts all the data in one column that I select.

**How to reproduce**
Store data in a table, using pgmodeler 1.0.0 alpha or earlier, upgrade to pgmodeler 1.0.0 or later.

**Expected behavior**
The data in the tables will be organized by columns and will be exportable.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Info about your desktop**
 - OS: Mac 
 - Version: Ventura
 - Window manager:
 - pgModeler version: 1.0.0 also tested on 1.0.1
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._
![Screenshot 2023-03-06 at 3 32 04 PM](https://user-images.githubusercontent.com/1256326/223223970-c16987d9-3b30-4f20-b2fa-40c8b472533d.png)

**Comment by nissane** [comment] 2023-03-06 20:43
Also, I see the xml used to contain:
<![CDATA[id•description⸣
BUY•Buy••••⸣
SEL•Sell••••]]>

but if I correct the data manually, the xml in the datamodel looks like:
	<![CDATA["id";"description"
"BUY";"Buy"
"SEL";"Sell"]]>


did the required format for storing data change? Is there a way to upgrade this?

**Comment by rkhaotix** [comment] 2023-03-06 22:41
The table data format was changed to standard CSV during the development of 1.0.0. So, you have to change manually from the old format to CSV as you already find out.

I can work on a patch for CLI to convert the old data format to CSV.

**Comment by nissane** [comment] 2023-03-07 02:09
Thanks, not necessary on my account.  I can manually update it.

**Comment by rkhaotix** [comment] 2023-03-07 17:07
In that case you have to escape the " not ;

So the correct format would be:

```
<![CDATA["id";"data"
"IQM";"<iframe style=""height:100%;width:100%;border:none""></iframe>"]]>
```

Alternatively, you can replace the double quotes in the ```style``` attribute by single quote.

**Comment by nissane** [comment] 2023-03-07 17:11
Perfect, that worked.

**Comment by nissane** [comment] 2023-03-07 23:48
apologies, for continually opening this.  I believe that if I change " to "" that works, but then if I load my model into pgmodeler and save it, it is replacing the " with &quot; and then it causes the data to break again (I get the message about the number of columns not matching the number or columns in the row.

I guess I will use single quotes, but just thought you should know that it's modify the data with "" and causing problems.

**Comment by rkhaotix** [comment] 2023-03-07 23:56
Don't worry, feel free to reopen this whenever you find needed. Thanks for reporting, I guess I know where the problem is!

**Comment by rkhaotix** [comment] 2024-01-09 11:41
@nissane Checking this issue again and I can confirm that it's now fixed. I'm closing it for now. If you still have problems, feel free to reopen it. Thanks.

**Closed by rkhaotix** 2024-01-09 11:41 UTC
Labels: bug
