### ISSUE TITLE
QUERY keyword not bolded

### ISSUE THREAD

**Issue by CaptainBloodz** [pgmodeler/pgmodeler#739] opened 2015-08-28 15:24 UTC
Same as ELSE clause, which works just fine though

**Comment by Ox0000** [comment] 2015-08-28 15:59
CaptainBloodz, thanks for reporting this!
Can you provide us with repro steps (executed steps, expected outcome, actual outcome)? Where did you encounter this?

**Comment by rkhaotix** [comment] 2015-08-28 16:12
The problem is simple to solve. The keyword is missing from
sql-highlight.conf file. Later today I'll provide the fix for this issue.
Em 28/08/2015 1:00 PM, "Ox0000" <notifications@github.com> escreveu:

**Closed** 2015-11-10 11:29 UTC
Labels: done, enhancement
