### ISSUE TITLE
Solving size_t/unsigned conversion warnings

### ISSUE THREAD

**Issue by lowjoel** [pgmodeler/pgmodeler#658] opened 2015-03-27 01:06 UTC
From #655.

Compiling on VC gives a lot of size_t/unsigned casting warnings. This issue is created to find a good solution for them.

**Comment by lowjoel** [comment] 2015-03-27 01:09
> > I think the best solution is to drop iteration over integers altogether.
> > A lot of the iteration is used over a container, so we should be using ranged-based for loops (or, at worst, using begin() and end())

> This will be a huge task. But let's discuss the better approach. I know that there are a lot of design problems in the code, when I started to write pgModeler I barely known about C++ and Qt. But today with all knowledge I've gained I could rewrite pgModeler using best practices but this is quite impossible to do alone. Almost 80k lines (in the last time I counted)..imagine start all over again. :(

There's no need to restart all over. We should fix these, one loop at a time...

> > There was even a std::map of unsigned

> Yes, I have some maps which keys are integers because in some operations i need to handle objects by their id in a sorted way... What I like in map is that as I add elements in it it will sort elements by key. Maybe there must be some other weird structure nothing that can't be changed.. It's not why I wrote the algorithm that it is the best solution. Many users pushed or suggested some interesting ones, like you've done.

Yes, I know... I'm not sure what the reason for that method was, but I was too afraid to change it...

> > I don't think that casting the 64- to 32-bit integer will be any faster on 64-bit CPUs, since both will compute any arithmetic operation in 1 clock cycle...

> I don't mean speed when talking about 64bit integers but memory usage, or in a low level, register usage.

Registers are 64 bits on 64-bit CPUs... memory usage might be doubled, but I think that's unlikely to be an issue in most cases... I don't think we stash huge lists of 64-bit numbers.

**Comment by rkhaotix** [comment] 2015-03-27 01:14
Right. So my concern for now is: what we do to VS warnings? I need to release a patch version soon and this problem is hammering my head. Do we just silence the warnings while we work in the fix or we merge the branch with the workaround (casts wherever needed)?

**Comment by lowjoel** [comment] 2015-03-27 01:15
We can just be like Linux and use /Wp64- to silence those warnings, until we find a nice fix for it.

**Comment by rkhaotix** [comment] 2015-03-27 01:22
Ok then. 

So, in order to put some order in the work to be done I think we should:

1) Replace index based loops by ranged or iterator based. This will eliminate the majority of warnings. 

2) Enhance the code design by using best practices when possible.

**Comment by lowjoel** [comment] 2015-03-27 01:29
Yup! I'll push PRs for what I can immediately fix. We can deal with the warnings a few at a time.

**Comment by rkhaotix** [comment] 2015-03-27 01:31
Alright! Thanks for such great help! 😁

**Comment by lowjoel** [comment] 2015-03-27 01:31
Oh, I see quite a few places where an implode or explode function would be useful...

Or we can just use boost::algorithm::join... which do you prefer?

**Comment by rkhaotix** [comment] 2015-03-27 01:38
I prefer stay just with Qt, STL and pure C++. Include another library is just another dependency to be resolved on the user's machine. :)

**Comment by rkhaotix** [comment] 2015-03-27 22:29
@lowjoel 

I was planning to change a bit our check list to this:

0) Replace unsigned by size_t mainly in classes that returns the size of internal containers or return internal elements by their index. This will help in the elimination of warnings too.

1) Replace index based loops by ranged or iterator based. This will eliminate the majority of warnings.

2) Enhance the code design by using best practices when possible.

I'm telling that because since we discussed about change the container iteration methods I need to specialize in functional programming (already studying it!) so that I can write good algorithms. If you prefer we can work in separated branches. But I really want to do the task 0 first. :)

**Comment by lowjoel** [comment] 2015-03-27 23:28
sure!

**Comment by rkhaotix** [comment] 2015-03-28 00:25
Thanks.

Just found a very strange issue with debug version. The software crashes when loading the "demo.dbm" file (sample model). It just this model. The error some kind of "incompatible vector iterators". The crazy thing is that in release mode the software runs fine.

I've messed up with my visual studio installation and I think tomorrow I'll post a screen shot of the error.

**Comment by lowjoel** [comment] 2015-03-28 00:26
If you have a stack trace I might be able to eyeball it.

**Comment by rkhaotix** [comment] 2015-03-28 00:30
I'm unable to do that for now. But you can try to reproduce it:

1) Compile pgModeler in debug mode in Qt creator
2) Deploy and run
3) Open the "demo.dbm"... crash!

My first suspect is that I've manually mapped the dll paths and maybe there must be some debug/release of dependencies being mixed.

**Comment by rkhaotix** [comment] 2015-03-28 12:09
@lowjoel Found the problem. It was my fault.

In method DatabaseModel::storeSpecialObjectXML() I was handling vectors iterating over them and in some moments erasing elements on them too. What I've discovered is that VC somehow invalidates the iterator and cause an assertion fail in the moment I try to access the next element (itr++). I believe that this is a good behavior avoiding the access to garbage memory portions. 

But in clang, gcc and MingW this situation does not happens or it happens and the own STL takes care of it (in those compilers) or just ignores (bad move!). I've never received a segmentation fault or something else. This code runs since GCC 4.5, the entire code base has 8-9 years and I'm starting to get worried about the quality of binary code produced by open source compilers and how they can be trusted! :/

What cause me more frustration is that we have a lot of situation like that throughout the other libraries. I was happy to see pgModeler compiling in VC++ and I think it's too early to celebrate! :'( 
I think we should move the VC port to a parallel branch and release test versions in order to other users try to find more crashes and bugs. 

Oh, one more thing, threaded operations just don't work in VC++ version! Sometimes crashing pgModeler! :(

**Comment by lowjoel** [comment] 2015-03-28 12:12
Yes, VC's STL catches a lot of bugs.

I don't think the VC port needs to be in a separate branch since the fixes we are doing for VC will work for the other compilers too. We don't release (Windows?) binaries so only the most crazy people will compile from source (or support your builds!)

In both situations, there shouldn't be a problem.

VC's runtime no longer come in the single-threaded version any more. What do you mean threaded operations do not work?

**Comment by rkhaotix** [comment] 2015-03-28 12:25
I have some operations that runs in separated thread. The export, diff and
reverse engineering are some examples. There I have cancel button to permit
user stop the operation while running... This behavior just doesn't work
and sometimes crash the application.

I would like to distribute 32 and 64 bit binaries to my clients but I'll to
wait though. :p

How is your work on the Vc port?
Em 28/03/2015 09:12, "Joel Low" <notifications@github.com> escreveu:

**Comment by lowjoel** [comment] 2015-03-28 12:27
Release builds don't work... they crash really quickly.

I think we should just fix the obvious crashes first. The STL warnings are quite bad. We can fix the threaded operations later on, I think.

If you want 64-bit binaries for Windows using mingw, there's the mingw-w64 project.

**Comment by rkhaotix** [comment] 2015-03-28 12:37
I tried to use mingw64 years ago without success. But I'll give it a try
again.

For my own sanity, I'll get back to the point where your first patch was
applied and rebranch it. I'll work on the new one doing my pending work and
merge to our common branch (code-changes). You can keep sending patches
that I'll merge and run them in VC. Once we solve all problems it will be
the official codebase!
Em 28/03/2015 09:27, "Joel Low" <notifications@github.com> escreveu:

**Comment by lowjoel** [comment] 2015-03-28 12:38
so which branch do I branch from? code-changes?

**Comment by rkhaotix** [comment] 2015-03-28 12:42
You can work on code-changes. It has the most recent patches you've sent.

**Comment by lowjoel** [comment] 2015-03-28 12:48
if I might request something, the branch naming could be made clearer :) I kept branching and rebasing to the wrong branch... also it might be good for the branch to have a descriptive name.

**Comment by rkhaotix** [comment] 2015-03-28 12:51
Hehehe. Fine!
I was working  alone all this time and the branch naming was fine to me!

Wan't something like "vc-port"? You can suggest one too

**Comment by lowjoel** [comment] 2015-03-28 12:52
yeah, vc-port or vc-build or something like that would be great. just remember to sync it with the main development branch over time...

**Comment by rkhaotix** [comment] 2015-03-28 13:19
Ok. I'll then rename it to 'vc-port'.

Do you mean merge develop into vc-port or the opposite?

**Comment by lowjoel** [comment] 2015-03-28 13:21
Develop to vc-port. Unless you want the reverse... Because I imagine that you might want to fix things in master/develop

**Comment by rkhaotix** [comment] 2015-03-28 13:34
Actually, my work flow is:

On master a have code for "stable" releases (0.8.0, 0.8.1, etc).
On develop a have code for "stable" in development releases (0.8.1-alpha, etc)

Any other branch are created and merged into develop first.. After that when the current version leaves the "in development" status I merge into master so that the stable code base can be found.

But don't worry, I'll keep mergin develop into vc-port to keep them synchronized.

**Closed** 2017-02-01 20:21 UTC
Labels: discussion, enhancement
