### ISSUE TITLE
Failed for check updates on MacOS 10.13.4

### ISSUE THREAD

**Issue by rodrigoalmeidanet** [pgmodeler/pgmodeler#1069] opened 2018-02-13 20:58 UTC
Hi Folks,

I try check updates on pgModeler for 0.9.1-beta version in MacOS 10.13.4 and I took this error:

<img width="512" alt="captura de tela 2018-02-13 18 56 37" src="https://user-images.githubusercontent.com/36429262/36173324-ced69968-10ef-11e8-8816-2099ff13bf2a.png">

Exist something to solve this problem with SSL connection?

Regards,
Rodrigo Almeida

**Comment by rkhaotix** [comment] 2018-02-13 23:14
Currently, you should disable automatic updates checking in Settings > General. 

I'm currently working on moving the site to a new domain and the SSL connection will fail for the domain .com.br

**Comment by rodrigoalmeidanet** [comment] 2018-02-18 03:29
Thanks Raphael.

**Comment by christiaanwesterbeek** [comment] 2018-04-25 12:05
You may close this issue since it's a duplicate of: https://github.com/pgmodeler/pgmodeler/issues/949

**Closed** 2024-01-03 16:02 UTC
Labels: oldissue
