### ISSUE TITLE
Import error: [ERR_ASG_NOT_ALOC_OBJECT] Assignment of not allocated object!

### ISSUE THREAD

**Issue by efedoso** [pgmodeler/pgmodeler#600] opened 2015-02-10 00:00 UTC
Error occurs when importing a database to get its design if functions are checked; same error with «Generate diff model» after adding a view:

[4] src/permission.cpp (33)
  Permission::Permission(BaseObject *)
    [ERR_ASG_NOT_ALOC_OBJECT] Assignment of not allocated object!

[3] src/databaseimporthelper.cpp (1838)
  void DatabaseImportHelper::createPermission(attribs_map &)
    [ERR_ASG_NOT_ALOC_OBJECT] Assignment of not allocated object!

[2] src/databaseimporthelper.cpp (403)
  void DatabaseImportHelper::createPermissions()
    [ERR_ASG_NOT_ALOC_OBJECT] Assignment of not allocated object!

[1] src/databaseimporthelper.cpp (534)
  void DatabaseImportHelper::importDatabase()
    [ERR_ASG_NOT_ALOC_OBJECT] Assignment of not allocated object!

[0] src/databaseimportform.cpp (351)
  void DatabaseImportForm::captureThreadError(Exception)
    [ERR_ASG_NOT_ALOC_OBJECT] Assignment of not allocated object!

![rg_rg340](https://cloud.githubusercontent.com/assets/10584385/6118655/2521cf88-b0c0-11e4-86a0-0975024230d4.jpg)

**Comment by rkhaotix** [comment] 2015-02-10 00:11
More details needed... Please send me a dump of the database (without data)
in order to reproduce and fix the problem.
Em 09/02/2015 22:00, "efedoso" <notifications@github.com> escreveu:

**Comment by efedoso** [comment] 2015-02-10 08:57
The one attached is a different one, but happens the same: when
importing if functions are selected. When functions are unchecked,
import is successful.

f2o

**Comment by rimbault** [comment] 2015-02-10 09:57
Same issue as #595 ...
Lots of import erreur on schema with trigger / function / check

[0] src/databaseimporthelper.cpp (621)
  void DatabaseImportHelper::createObject(attribs_map&)
    [ERR_OBJECT_NOT_IMPORTED] The object `trigger_suivi_flux_migration' (Déclencheur) could not be imported due to one or more errors! Check the exception stack for more details.

[3] src/databasemodel.cpp (5129)
  Trigger* DatabaseModel::createTrigger()
    [ERR_REF_OBJ_INEXISTS_MODEL] The object `trigger_suivi_flux_migration' (Déclencheur) is referencing the object `public.documents_a' (Table) which was not found in the model!

[2] src/databasemodel.cpp (5253)
  Trigger* DatabaseModel::createTrigger()
    [ERR_REF_OBJ_INEXISTS_MODEL] The object `trigger_suivi_flux_migration' (Déclencheur) is referencing the object `public.documents_a' (Table) which was not found in the model!
       ** <trigger name="trigger_suivi_flux_migration" firing-type="AFTER" per-line="true" constraint="false"
         ins-event="true" del-event="false" upd-event="true" trunc-event="false"
         table="public.documents_a">
                <function signature="public.trigger_suivi_flux_migration()"/>
</trigger>



[1] src/databaseimporthelper.cpp (1562)
  void DatabaseImportHelper::createTrigger(attribs_map&)
    [ERR_REF_OBJ_INEXISTS_MODEL] The object `trigger_suivi_flux_migration' (Déclencheur) is referencing the object `public.documents_a' (Table) which was not found in the model!
       ** <trigger name="trigger_suivi_flux_migration" firing-type="AFTER" per-line="true" constraint="false"
         ins-event="true" del-event="false" upd-event="true" trunc-event="false"
         table="public.documents_a">
                <function signature="public.trigger_suivi_flux_migration()"/>
</trigger>

**Comment by rkhaotix** [comment] 2015-02-10 11:18
@efedoso Found the problem! The issue was related to a permission assigned to a function. In the moment a permission was being create the function name was wrongly set and the import process could not find the proper object, raising the error. Fix already done. Thanks for reporting.

@rimbault I'm still investigating this issue. Since the dump you've sent me was working fine I'm trying to figure out a situation where the error can be reproduced.

**Comment by rimbault** [comment] 2015-02-10 11:22
@rkhaotix : i'm trying to reproduce the bug on a simple database. But, as soon as i pg_dump and restore a database on my desktop the import from pgmodeler go fine :(

**Comment by rkhaotix** [comment] 2015-02-10 11:24
@rimbault I have a suspect. The time you've sent me the dump I noticed that you have a foreign table and some other objects that pgModeler formally does not supports. The import process works but if you see the resulting model, the foreign table isn't there. I've already registered a feature request #597 for this. :(

**Comment by rimbault** [comment] 2015-02-10 11:32
@rkhaotix : yes, in some case there is FDW.
But other databases juste crash on trigger (no FDW or other contrib).
Funny : if i dump the schema and create the news database on the same instance (without data), import work fine.
Most of my instance have been pg_upgraded (to 9.2 or 9.3) : new suspect ?

**Comment by rkhaotix** [comment] 2015-02-10 11:36
I don't think that the upgrade from 9.2 to 9.3 could cause such problem. It's hard to imagine other situations without investigate the real database which is causing the error.

**Comment by efedoso** [comment] 2015-02-10 13:11
@rkhaotix Is the binary also fixed? I tried to compile to no avail, so I'd rather redowload it.

**Comment by rkhaotix** [comment] 2015-02-10 13:21
@efedoso No. The fix is currently only in the develop branch and will be available to final users via binaries only on the next release 0.8.0.

**Closed** 2015-02-28 18:05 UTC
Labels: bug, fixed
