### ISSUE TITLE
Custom type properties order is not respected (export and diff)

### ISSUE THREAD

**Issue by FGRibreau** [pgmodeler/pgmodeler#1478] opened 2020-10-14 10:01 UTC
**Bug description**

If we create a custom type as below:

```sql
create schema api;
create type api.product as
(
    id                  uuid,
    sku                 varchar(255),
    name                text,
    description         text,
    image               text,
    category_id         uuid,
    contract_version_id uuid,
    created_at          timestamptz,
    published_at        timestamptz
);
```

We don't get the same DDL in the exported SQL from PG Modeler (and thus the diff feature).

The order is semantically important. Projects like https://github.com/PostgREST/postgrest requires that the type matches a view columns order (in case you create a view that yield a specific type instead of raw columns).

**How to reproduce**

- create a custom type:

```sql
create schema api;
create type api.product as
(
    id                  uuid,
    sku                 varchar(255),
    name                text,
    description         text,
    image               text,
    category_id         uuid,
    contract_version_id uuid,
    created_at          timestamptz,
    published_at        timestamptz
);
```

- then generate the source code from pgModeler either with Manage tab, Export tab, or Diff tab :

```sql
CREATE TYPE api.product AS
(
  image text COLLATE pg_catalog."default",
  description text COLLATE pg_catalog."default",
  name text COLLATE pg_catalog."default",
  sku character varying(255) COLLATE pg_catalog."default",
  published_at timestamp with time zone,
  created_at timestamp with time zone,
  contract_version_id uuid,
  category_id uuid,
  id uuid
);
```

- observe that the type properties don't have the same order.

**Expected behavior**

Consistent order between declaration time and export/diff time.

**Info about your desktop**
 - OS: MacOS
 - Version: Catalina
 - pgModeler version: v0.9.3-beta1
 - Qt version: 20201002 Qt 5.15.1

### We are willing to pay for a priority fix on this @rkhaotix :+1:

**Comment by rkhaotix** [comment] 2020-10-14 14:32
@FGRibreau Strangely, I couldn't reproduce that order changing behavior you mentioned.

I used the snippet you posted to create the custom type and then generated its source code from Manage view (which would be the same effect as importing the data type into a new model and then export it to SQL script or preview its source). 

I'm using PostgreSQL 12 and pgModeler 0.9.3 (under development, but the code base is pretty the same as 0.9.3-beta1).

Note that the changes in the data type names of the columns (in the source code panel on Manage view) are not controlled by pgModeler. When importing columns of a table, pgModeler will use the OID of the data type associated with the column and then retrieve its name via ```OID::regtype::text```. For example, ```timestamptz``` is an alias to ```timestamp with time zone```, even if you have written ```timestamptz``` the column will always be imported as ```timestamp with time zone``` because that cast works this way. The same is valid for ```varchar``` vs. ```character varying``` and so on... Semantically, nothing changes between what you have typed in the DDL and what was imported, but if you really need that the data type names be the same then the solution may be a bit complicated.

![image](https://user-images.githubusercontent.com/2205476/96001594-965de900-0e0e-11eb-91e5-53819ea5d6ac.png)

**Comment by FGRibreau** [comment] 2020-10-14 14:52
That's weird indeed, I'm on PostgreSQL (`bitnami/postgresql:12.3.0` docker image) and pgModeler `v0.9.3-beta1 20201002 Qt 5.15.1`and have that issue with the specified test example :/

**Comment by FGRibreau** [comment] 2020-10-20 08:36
@rkhaotix do you think it was related with a change in 0.9.3 that was not there in 0.9.3-beta1?

**Comment by rkhaotix** [comment] 2020-10-20 09:04
@FGRibreau I doubt it. Anyway, I will try to reproduce the problem in the same version as you did and see what happens.

**Comment by FGRibreau** [comment] 2020-11-02 09:34
@rkhaotix Hello Raphael, any updates on the 0.9.3 release? 
(It seems we found another issue, @amenant will submit it in another ticket in the next minutes :))

**Comment by rkhaotix** [comment] 2020-11-02 16:08
@FGRibreau Hi, sorry for not responding you. I did not test it yet. Since last time we have talked I developed carppal tunnel syndrome in my right hand. So I'm treating it first and as soon as I get recovered I will work on the pending issues. Unfortunately, my condition will cause delay on the release of 0.9.3! I'm really sorry. :(

**Comment by rkhaotix** [comment] 2020-11-09 18:32
Hi again @FGRibreau 

Just responding to you, I've tested the sample SQL in pgModeler 0.9.3-beta1 and nothing wrong happened (see the attached image). For now, I'm closing this issue in preparation for 0.9.3. If you still see this problem happening with the stable 0.9.3 feel free to reopen it, okay?

![image](https://user-images.githubusercontent.com/2205476/98581496-54568480-22a0-11eb-8ca3-3dd5aa699d47.png)

**Closed by rkhaotix** 2020-11-09 18:32 UTC
Labels: bug

**Comment by FGRibreau** [comment] 2020-11-09 18:36
Hum, were you also on `20201002 Qt 5.15.1`?

**Comment by rkhaotix** [comment] 2020-11-09 18:45
Yep! 

![image](https://user-images.githubusercontent.com/2205476/98583002-7d781480-22a2-11eb-8fdb-8cdaba49f8f1.png)

**Comment by FGRibreau** [comment] 2020-11-10 14:09
I can't reproduce it anymore, I got:

```sql
-- object: api.product | type: TYPE --
-- DROP TYPE IF EXISTS api.product CASCADE;
CREATE TYPE api.product AS
(
  id uuid,
  sku character varying(255),
  name text,
  description text,
  image text,
  category_id uuid,
  contract_version_id uuid,
  created_at timestamp with time zone,
  published_at timestamp with time zone
);
-- ddl-end --
ALTER TYPE api.product OWNER TO postgres;
-- ddl-end --
```

However, I think I understood the underneath issue, if you take a look at the wrong output:

```sql
CREATE TYPE api.product AS
(
  image text COLLATE pg_catalog."default",
  description text COLLATE pg_catalog."default",
  name text COLLATE pg_catalog."default",
  sku character varying(255) COLLATE pg_catalog."default",
  published_at timestamp with time zone,
  created_at timestamp with time zone,
  contract_version_id uuid,
  category_id uuid,
  id uuid
);
```

as you can see, the type properties were ordered by the COLLATE property.
It seems  it does not happen anymore, so that's good news!
