### ISSUE TITLE
failed check for updates

### ISSUE THREAD

**Issue by prtome** [pgmodeler/pgmodeler#1107] opened 2018-04-18 16:51 UTC
Hello
when I run Check for updates I get 
The update notifier failed to check for new versions! Please, verify your internet connectivity and try again! Connection error returned: 0 - SSL handshake failed.

I have currently V0.9.1-beta Build 20180122, paid version

thanks

**Comment by jkirkpatrick** [comment] 2018-04-19 19:41
See #1069

**Comment by christiaanwesterbeek** [comment] 2018-04-25 12:05
You may close this issue since it's a duplicate of: https://github.com/pgmodeler/pgmodeler/issues/949

**Closed** 2024-01-03 16:01 UTC
Labels: oldissue
