### ISSUE TITLE
Could not execute the SQL command. `ERROR:  database "xxx" is being accessed by other users"

### ISSUE THREAD

**Issue by tapir** [pgmodeler/pgmodeler#1221] opened 2018-12-13 18:08 UTC
**Bug description**
When trying to export my db model after using the Database Explorer it complains that there is another session going on.

**How to reproduce**
1- Export your model to your PostgreSQL server
2- Use Database Explorer to connect to the said server and database
3- Disconnect from the database in Database Explorer
4- Try to export the model with drop DB enabled

**Expected behavior**
Export should work once the Database Explorer is no longer connected to the said database. Somehow connection stays open.

**Workaround**
Close pgModeler and reopen. Then export works again.

**Info about your desktop**
 - OS: Arch
 - Version: Latest
 - Window manager: Gnome
 - pgModeler version: 0.9.2 alpha
 - Qt version: 5.12

**Screenshot**
![screenshot from 2018-12-13 21-05-36](https://user-images.githubusercontent.com/223984/49958188-1b2e0200-ff1b-11e8-895d-fa4ebad7ba6e.png)

**Comment by tapir** [comment] 2019-01-01 13:55
Looks like fixed on latest version

**Comment by tapir** [comment] 2019-01-01 13:59
Sorry I was mistaken. The issue still persists.

**Comment by rkhaotix** [comment] 2019-12-03 13:12
I still can't reproduce this problem. I'll be closing it but if you can give more info or steps that leads to the error, please reopen it and I'll investigate.

**Closed by rkhaotix** 2019-12-03 13:12 UTC
