### ISSUE TITLE
Zoom different from 100% hides column names in Windows 10

### ISSUE THREAD

**Issue by zardo** [pgmodeler/pgmodeler#1436] opened 2020-05-22 20:37 UTC
**Bug description**
Zoom different from 100% hides column names.

**How to reproduce**
Change zoom in Windows 10.

**Expected behavior**
Keep showing column names when zoom is not 100%.

**Screenshots**
![image](https://user-images.githubusercontent.com/6507492/82707597-c5eb3980-9c52-11ea-8d77-331fa11e409a.png)

**Info about your desktop**
 - OS: Windows 10
 - Version: 10.0.18363 Build 18363
 - Window manager: Windows?
 - pgModeler version: v0.9.3-alpha1 build: 20200520 Qt 5.14.2
 - Qt version: 5.14.2

**Stacktrace / Debug info**
Didn't crash.

**Additional info**
N/A

**Comment by rkhaotix** [comment] 2020-05-22 22:25
This is an intermittent problem that I never was able to reproduce :/

Tried many times in different Qt versions and pgModeler version combined and could not see this "bug" happen. 

Did you try to change the default font used in the database design? Change default font site? Any other clues that may help discover what's going on?

**Comment by hairlesshobo** [comment] 2020-05-27 14:53
In case this helps at all, I am also having the same issue with zooming out on Windows 10 (version 1803). I did notice that, if I change the font size to 8.5 or 9.5 instead of the default 9, then the text shows back up.

**Comment by rkhaotix** [comment] 2020-05-27 15:27
Thanks for that @hairlesshobo 

This is something that helps to investigate the problem. Did you change the font family as well or just the size?

**Comment by hairlesshobo** [comment] 2020-05-27 15:53
Just changed the size, nothing else. Also, don't know if this is relevant or not, but one of my screens is 2650x1440 (but i do not use display scaling.. all of my displays are at 100% zoom). I tried it on both a 1920x1080 screen asnd the 2650x1440, and it did not make a difference, only changing the font size larger or smaller made a difference.

**Comment by rkhaotix** [comment] 2020-05-27 16:09
This sounds a bug on Qt framework, I will investigate on project's forums. Thanks once more

**Comment by zardo** [comment] 2020-05-28 10:26
@rkhaotix @hairlesshobo Thanks for the investigation and help.

I tested with several different font families and sizes and seems that the **ONLY** way to reproduce the bug is with the font family **_MS Shell Dlg 2_** at **_9pt_** which is the default in my installation.

![image](https://user-images.githubusercontent.com/6507492/83130052-17148680-a0b4-11ea-8267-b7b607b5a33d.png)

Maybe changing the default font on Windows is an easier solution.

Thanks again!

**Comment by hairlesshobo** [comment] 2020-05-28 11:59
@zardo glad it helped!

**Comment by rkhaotix** [comment] 2020-11-09 18:08
I'm closing this issue since I couldn't confirm it after lots of tests. In case of it happens again, feel free to reopen it.

**Closed by rkhaotix** 2020-11-09 18:08 UTC
