### ISSUE TITLE
Cannot apply the operator jsonb_path_ops to a GIN index

### ISSUE THREAD

**Issue by pixelbadger** [pgmodeler/pgmodeler#852] opened 2016-08-04 12:30 UTC
I cannot find a way to assign the jsonb_path_ops operator to a GIN index on one of my jsonb columns.

As per [this documentation](https://www.postgresql.org/docs/9.5/static/datatype-json.html), section 8.14.4, we can create an index of the form:

``` SQL
CREATE INDEX idxginp ON api USING GIN (jdoc jsonb_path_ops);
```

This doesn't appear to be possible in pgModeler.

**Comment by rkhaotix** [comment] 2016-08-04 12:35
Yes. pgModeler doesn't support that yet.
You can create the index manually as you need by appending the DDL you mentioned in the related table. Use the "Custom SQL" button at table's dialog

**Comment by rkhaotix** [comment] 2016-08-04 12:39
Anyway I'll mark this issue as feature request in order to implement it in the next releases. Thanks!

**Comment by pixelbadger** [comment] 2016-08-04 12:41
Great, thanks for your response – use of custom SQL has solved the issue for now.

**Comment by rkhaotix** [comment] 2017-02-22 12:54
@pixelbadger Hi. Sorry respond your comment after soooo long...

Well, analyzing the details again I could notice that if you use an element in the index for an expression instead of a column you can achieve the desired result. So, if you just write ```jdoc jsonb_path_ops``` as an expression element the index sql will be the same as you've mentioned.

So, despite my last comment to add a patch for this, I don't see the need right now.
I'll close this issue. If you really see a need to implement the feature I'm open for discussion :)

**Comment by pixelbadger** [comment] 2017-03-01 13:57
@rkhaotix I've tried this and unfortunately it doesn't work. The resulting SQL is:

```sql
CREATE INDEX idx_jsonb_test_jsondata ON public.jsonb_test
USING gin
(
    (jsondata jsonb_path_ops)
);
```

The parentheses around `jsondata jsonb_path_ops` causes a synax error.

For reference, I'm using v 0.9.0-alpha, running against a v9.6 Postgres server.

**Comment by rkhaotix** [comment] 2017-03-01 14:00
Ok @pixelbadger.

I'm reopening this issue in order to provide thw the fix then. Thanks for your feedback!

**Comment by BathoryPeter** [comment] 2018-05-17 21:50
I'm faced with the same problem as pixelbadger had. Created an index with an expression (```left(text::text, 255) gist_trgm_ops```), but pgModler generated SQL with wrong, doubled parentheses. I tried to move gist_trgm_ops from expression to operator class field, but this list is completely empty and I cannot add op classes to pgModeler.
As a workaround I removed parenthesis from schemas/sql/idxelement.sch line 10, but is its against the Postgres documentation.

**Comment by rkhaotix** [comment] 2018-05-17 22:26
@BathoryPeter which release are you using? I thought I had fixed this problem! If the issue still persists in the current release, I'm gonna look into it once more.

**Comment by BathoryPeter** [comment] 2018-05-17 22:30
v0.9.1 build: 20180511 (built from 0.9.1 git branch)

**Comment by rkhaotix** [comment] 2018-05-17 22:58
Guys, I have to appologize! 
Actually, there's no need to fix pgModeler. 

This is one of the cases where we need to deal with "fake objects". In that case, we need to create a fake operator class called ```jsonb_path_ops``` for @pixelbadger  or ```gist_trgm_ops``` for @BathoryPeter .

To do that, create a simple operator class under ```pg_catalog``` (it can be the same as the one I've created) . Just remember to check ```Disable SQL code``` to make pgModeler ignore this object when genarating the code of the whole database.

![op_class](https://user-images.githubusercontent.com/2205476/40207666-1b7b34bc-5a0c-11e8-87fa-9d380bf73d59.png)

Once the object is created you can use it in the index element like I did here:

![index](https://user-images.githubusercontent.com/2205476/40207729-67b02efa-5a0c-11e8-9861-ac36de7421d7.png)

And the resulting SQL for the index was:

![index_source](https://user-images.githubusercontent.com/2205476/40207746-820a0488-5a0c-11e8-939b-13e762bf8a53.png)

**Comment by BathoryPeter** [comment] 2018-05-23 12:26
Hi, Raphael!

Thank you so much for the tip (and this excellent program)!

I succeeded to add a new operator class but despite your screenshots it was not easy.
Just for those who is in the same trouble:
* Create the operator class in the same schema as the extension (for me it was "public")
* Change Element type to Storage
* Click to + button (you can set proper types but it doesn't matter since it will be a dummy object)
* And of course don't forget to check Disable SQL code

So it works, but not straightforward at all.
The root of the problem is that the operator classes (and I think many other objects) are created by extensions dynamically and pgModeler doesn't know about them.
On my opinion your 'select dialog' concept is too strict for those objects. It would be more simple if I can select the object from the dialog OR enter a free text object name (because I'm sure it will be exists at this point).

**Comment by johnaschroeder** [comment] 2019-06-07 20:19
I have a similar issue creating the following pg_trgm gin index.  The sql to create it by hand is:
```
CREATE INDEX clinics_clinic_name_trgm_idx ON vetmed.clinics USING gin (clinic_name vetmed.gin_trgm_ops);
```
I followed the above instructions and diff now creates the correct sql in pgmodeler against my production db.  The problem i'm facing is now my model doesn't validate.  pgModeler validation throws the following error:
```
Could not execute the SQL command.
 Message returned: `ERROR:  operator class "gin_trgm_ops" does not exist for access method "gin"
```
I have pg_trgm installed as an extension in pgmodeler.  I've also done this by hand in my local dev database.  It makes 'like' queries an order of magnitude faster.  I'm stumped.  FYI I'm on v0.9.2-beta build 20190531 Qt 5.12.3.

**Comment by rkhaotix** [comment] 2019-06-12 11:38
Hi @johnaschroeder 

Sorry the delay on response. Could you provide your model or just a small sample that causes the problem you're facing?

**Comment by johnaschroeder** [comment] 2019-06-12 11:50
Yes, will do. I’ll have it to you in the next few days.

**Closed** 2019-12-03 13:15 UTC
Labels: enhancement
